import assert from 'node:assert/strict';
import test from 'node:test';
import { MARKER_NAMESPACE, renderPresetRow, setEntryConfig, upsertMarkerBlock } from '../lib/preset-yaml.js';

/**
 * A representative dump of a preset's plugin list — same shape as
 * `agentPresets.readDocument()` returns (nested `compaction` group, one child that
 * already carries a `config:` block). Whether dsh can parse what we emit is proven
 * by the isolated real-boot check; these tests pin the surgery itself.
 */
const PLUGINS = `- id: persona
  name: '@deepseek-ai/dsh-persona'
  config:
    suffix: Your working directory is {{cwd}}.
- id: compaction
  name: cordis:group
  group: true
  isolate:
    compaction: true
    toolResultPruner: true
  config:
    - id: compaction-basic
      name: '@deepseek-ai/dsh-compaction-basic'
    - id: command-compact
      name: '@deepseek-ai/dsh-command-compact'
    - id: tool-result-pruner
      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'
      config:
        thresholdChars: 8192
        headChars: 4096
        tailChars: 1024
- id: delegation
  name: cordis:group
  group: true
`;

const CONFIG = {
	thresholdRatio: 0.8,
	headroomTokens: 0,
	maxTokens: 16384,
	summarizationProvider: 'opencode-go-v41',
	summarizationModel: 'deepseek-v4.1-flash',
	modelPolicies: [
		{ provider: 'b70-sycl', model: '/models/Qwen3.8-27B-Q4_K_M.gguf', thresholdRatio: 0.8, headroomTokens: 9831 },
		{ provider: 'bonsai-8gb', model: '/home/gwang/bonsai2/models/mtp-lean.gguf', thresholdRatio: 0.8, headroomTokens: 0 }
	]
};

test('setEntryConfig inserts a config block into a nested, config-less entry only', () => {
	const edited = setEntryConfig(PLUGINS, 'compaction-basic', CONFIG);
	assert.ok(edited !== null);
	assert.equal(
		edited,
		PLUGINS.replace(
			"    - id: compaction-basic\n      name: '@deepseek-ai/dsh-compaction-basic'\n",
			[
				"    - id: compaction-basic",
				"      name: '@deepseek-ai/dsh-compaction-basic'",
				'      config:',
				'        thresholdRatio: 0.8',
				'        headroomTokens: 0',
				'        maxTokens: 16384',
				'        summarizationProvider: opencode-go-v41',
				'        summarizationModel: deepseek-v4.1-flash',
				'        modelPolicies:',
				'          - provider: b70-sycl',
				'            model: /models/Qwen3.8-27B-Q4_K_M.gguf',
				'            thresholdRatio: 0.8',
				'            headroomTokens: 9831',
				'          - provider: bonsai-8gb',
				'            model: /home/gwang/bonsai2/models/mtp-lean.gguf',
				'            thresholdRatio: 0.8',
				'            headroomTokens: 0',
				''
			].join('\n')
		),
		'the block lands directly under the entry name, at the entry key indent + 2'
	);
	// Everything else is untouched, including the sibling that already has a config.
	assert.ok(edited.includes('        thresholdChars: 8192'));
	assert.ok(edited.includes('- id: delegation'));
});

test('setEntryConfig is idempotent and replaces an existing config block', () => {
	const once = setEntryConfig(PLUGINS, 'compaction-basic', CONFIG);
	const twice = setEntryConfig(once, 'compaction-basic', CONFIG);
	assert.equal(twice, once, 're-running the generator must not duplicate the block');

	// A config without the optional summarization route and without policies.
	const replaced = setEntryConfig(once, 'compaction-basic', { thresholdRatio: 0.7, headroomTokens: 0, maxTokens: 16384, modelPolicies: [] });
	assert.ok(replaced.includes('        thresholdRatio: 0.7'));
	assert.ok(!replaced.includes('thresholdRatio: 0.8'));
	assert.ok(!replaced.includes('modelPolicies:'), 'an empty policy list emits nothing');
	assert.ok(!replaced.includes('summarizationProvider:'), 'an absent summarization route emits nothing');

	const pruner = setEntryConfig(PLUGINS, 'tool-result-pruner', { thresholdRatio: 1, headroomTokens: 0, maxTokens: 1024 });
	assert.ok(pruner.includes('        thresholdChars: 8192') === false, 'the pre-existing body is replaced, not appended to');
	assert.ok(pruner.includes('        thresholdRatio: 1'));
	assert.ok(pruner.includes('- id: delegation'), 'the following group survives the replacement');
});

test('setEntryConfig reports an unknown entry instead of guessing', () => {
	assert.equal(setEntryConfig(PLUGINS, 'compaction-basic-typo', CONFIG), null);
	assert.equal(setEntryConfig('', 'compaction-basic', CONFIG), null);
});

test('renderPresetRow produces an insert row with the plugin list indented under plugins', () => {
	const row = renderPresetRow({
		rowId: 'preset-standard-tuned',
		presetId: 'standard-tuned',
		name: '标准模式 (调优压缩)',
		description: 'generated by /trim preset: compaction at 80 % of each routed window',
		order: 1.5,
		pluginsYaml: '- id: persona\n  name: \'@deepseek-ai/dsh-persona\'\n'
	});
	assert.equal(
		row,
		[
			'- insert:',
			'    - id: preset-standard-tuned',
			"      name: '@deepseek-ai/dsh-agent-preset'",
			'      config:',
			'        id: standard-tuned',
			"        name: '标准模式 (调优压缩)'",
			"        description: 'generated by /trim preset: compaction at 80 % of each routed window'",
			'        order: 1.5',
			'        plugins:',
			"          - id: persona",
			"            name: '@deepseek-ai/dsh-persona'"
		].join('\n')
	);
});

test('upsertMarkerBlock appends once and then replaces in place', () => {
	const existing = '# user comment\n- id: web-search-deepseek\n  disabled: true\n';
	const first = upsertMarkerBlock(existing, 'preset-standard-tuned', '- insert:\n    - id: preset-standard-tuned');
	assert.equal(first.replaced, false);
	assert.ok(first.text.startsWith('# user comment'));
	assert.ok(first.text.includes(`# >>> ${MARKER_NAMESPACE}: preset-standard-tuned`));
	assert.ok(first.text.includes(`# <<< ${MARKER_NAMESPACE}: preset-standard-tuned <<<`));

	const second = upsertMarkerBlock(first.text, 'preset-standard-tuned', '- insert:\n    - id: preset-standard-tuned # v2');
	assert.equal(second.replaced, true);
	assert.equal(second.text.includes('# v2'), true);
	assert.equal(second.text.split(`# >>> ${MARKER_NAMESPACE}: preset-standard-tuned`).length - 1, 1, 'exactly one block remains');
	assert.ok(second.text.startsWith('# user comment'), 'the user content above the block is preserved');

	const intoEmpty = upsertMarkerBlock('', 'preset-x', '- insert: []');
	assert.equal(intoEmpty.replaced, false);
	assert.ok(intoEmpty.text.endsWith('\n'));
});
