import assert from 'node:assert/strict';
import test from 'node:test';
import { planCompactionTuning } from '../lib/compaction-spec.js';
import { buildHostTunedPatch, buildTunedPresetPatch } from '../lib/tuned-preset.js';

const BASE = `- id: persona
  name: '@deepseek-ai/dsh-persona'
- id: compaction
  name: cordis:group
  group: true
  config:
    - id: compaction-basic
      name: '@deepseek-ai/dsh-compaction-basic'
    - id: command-compact
      name: '@deepseek-ai/dsh-command-compact'
- id: delegation
  name: cordis:group
`;

const PLAN = planCompactionTuning({
	routes: [{ provider: 'mock', model: 'mock-model', contextWindow: 65536, maxTokens: 4096 }],
	targetRatio: 0.75
});

test('the overlay carries the tuned preset and points the registry at it', () => {
	const { patch, plugins, registryRow } = buildTunedPresetPatch({ base: BASE, presetId: 'standard-tuned', name: 'Standard (tuned 75%)', order: 1.5, plan: PLAN });
	assert.match(patch, /^# Generated by dsh-command-context-trim/);
	assert.match(patch, /- id: preset-standard-tuned/);
	assert.match(patch, /name: '@deepseek-ai\/dsh-agent-preset'/);
	assert.match(patch, /id: standard-tuned/);
	assert.match(patch, /order: 1\.5/);
	// The tuned compaction config rode along inside the cloned group.
	assert.match(plugins, /thresholdRatio: 0\.75/);
	assert.match(plugins, /headroomTokens: 0/);
	assert.match(plugins, /modelPolicies:/);
	assert.match(plugins, /- id: command-compact/, 'siblings in the group survive');
	assert.match(registryRow, /default: standard-tuned/);
	assert.match(registryRow, /selectedDefault: standard-tuned/);
	assert.ok(patch.endsWith('\n'));
});

test('the registry row can override an existing one instead of inserting', () => {
	const insert = buildTunedPresetPatch({ base: BASE, presetId: 'x', plan: PLAN });
	const override = buildTunedPresetPatch({ base: BASE, presetId: 'x', plan: PLAN, registryMode: 'override' });
	assert.match(insert.patch, /- insert:\n    - id: agent-preset-registry/);
	assert.match(override.patch, /\n- id: agent-preset-registry/);
	assert.equal(override.patch.includes('- insert:\n    - id: agent-preset-registry'), false);
});

test('a base without compaction-basic, or a missing plan, is refused', () => {
	assert.throws(() => buildTunedPresetPatch({ base: '- id: persona\n', presetId: 'x', plan: PLAN }), /declares no compaction-basic entry/);
	assert.throws(() => buildTunedPresetPatch({ base: BASE, presetId: 'x' }), /a compaction plan is required/);
	assert.throws(() => buildTunedPresetPatch({ base: '', presetId: 'x', plan: PLAN }), /a base composition is required/);
	assert.throws(() => buildTunedPresetPatch({ base: BASE, presetId: '  ', plan: PLAN }), /a preset id is required/);
});

test('host mode writes the tuning onto the profile plane row', () => {
	const { patch, config } = buildHostTunedPatch({ plan: PLAN });
	assert.match(patch, /--mode host/);
	assert.match(patch, /- id: compaction-basic\n  name: '@deepseek-ai\/dsh-compaction-basic'\n  config:/);
	assert.match(patch, /    thresholdRatio: 0\.75/);
	assert.match(patch, /    modelPolicies:/);
	assert.equal(patch.includes('- insert:'), false, 'a row override, not an inserted preset');
	assert.equal(config.thresholdRatio, 0.75);
	assert.throws(() => buildHostTunedPatch({}), /a compaction plan is required/);
});
