/**
 * `/trim preset` — generate a compaction-tuned agent preset from the live routes.
 *
 * Why a preset and not a runtime knob: compaction's policy is read at composition
 * time by a `compaction-basic` instance that lives inside an agent-preset isolate
 * realm. A host-plane plugin cannot see or reconfigure that instance, so the only
 * honest way to move the threshold is to contribute a preset row — which 0.1.7 made
 * an ordinary patch row (`@deepseek-ai/dsh-agent-preset`).
 *
 * The generated preset is a **clone of the preset in use**, read through
 * `agentPresets.readDocument()` (already-evaluated plugin list), with only the
 * `compaction-basic` entry's `config:` replaced. Cloning at generation time is what
 * keeps it current: a hand-copied preset rots the moment dsh changes its own
 * composition.
 *
 * Persistence is a marker-delimited block in the profile patch, so the result is
 * reviewable, idempotent, and removable by deleting the block.
 *
 * @module dsh-command-context-trim/preset-tune
 */
import { copyFile, readFile, rename, writeFile } from 'node:fs/promises';
import { planCompactionTuning } from './compaction-spec.js';
import { renderPresetRow, setEntryConfig, upsertMarkerBlock } from './preset-yaml.js';
import { latestRoute } from './target.js';

/** Suffix appended to the base preset id for the generated one. */
export const TUNED_PRESET_SUFFIX = '-tuned';

/**
 * Generate (and optionally persist) a compaction-tuned preset.
 * @param ctx - plugin context carrying `agentPresets`, `configEditor`, `llm`.
 * @param config - resolved plugin configuration.
 * @param request - `{ agent, signal, requestedRoute?, check? }`.
 * @returns `{ result }` — a command result.
 */
export async function tuneCompactionPreset(ctx, config, request) {
	const { agent, signal, requestedRoute, check = false, list = false } = request;
	if (list) return { result: { kind: 'success', text: await renderRouteList(ctx, agent, signal, config) } };
	const registry = ctx.get?.('agentPresets');
	if (registry === undefined) {
		return failure(
			'This profile composes no agent-preset registry, so there is nothing to generate into.\n' +
				'Presets come from the web app bundle (`dsh-web-app/presets/*.patch.yml`); a headless or minimal profile has none.'
		);
	}
	const roster = await registry.remoteExportList();
	const base = pickBasePreset(roster, agent);
	if (base === undefined) return failure('The preset registry has no presets to clone.');
	let document;
	try {
		document = await registry.readDocument(base.id);
	} catch (error) {
		return failure(`Cannot read preset "${base.id}": ${describe(error)}`);
	}
	const routes = await collectRoutes(ctx, agent, signal);
	if (routes.length === 0) {
		return failure('No routable provider/model pairs were found, so there is nothing to size a threshold for.');
	}
	const summarizationRoute = requestedRoute ?? config.compactionRoute;
	let plan;
	try {
		plan = planCompactionTuning({ routes, targetRatio: config.compactionTargetRatio, summarizationRoute });
	} catch (error) {
		return failure(describe(error));
	}
	const spliced = setEntryConfig(document.content, 'compaction-basic', plan.config);
	if (spliced === null) {
		return failure(`Preset "${base.id}" declares no compaction-basic entry, so its threshold cannot be tuned.`);
	}
	const presetId = `${base.id}${TUNED_PRESET_SUFFIX}`;
	const rowId = `preset-${presetId}`;
	const rowText = renderPresetRow({
		rowId,
		presetId,
		name: `${document.name ?? base.name ?? base.id} (tuned ${(config.compactionTargetRatio * 100).toFixed(0)}%)`,
		description:
			`Generated by /trim preset: compaction fires at ${(config.compactionTargetRatio * 100).toFixed(0)} % of each routed window` +
			`${summarizationRoute === undefined ? '' : `, summarization on ${summarizationRoute.provider}/${summarizationRoute.model}`}.`,
		order: (base.order ?? 1) + 0.5,
		pluginsYaml: spliced
	});
	const report = renderReport({ base, plan, presetId, rowId, rowText, check });
	if (check) return { result: { kind: 'success', text: report } };
	const profile = ctx.get?.('profileContext');
	const patchPath = profile?.patchPath;
	if (typeof patchPath !== 'string' || patchPath.length === 0) {
		return failure(`Cannot locate the profile patch to write into.\n\n${report}`);
	}
	let landed;
	try {
		landed = await persistBlock(patchPath, rowId, rowText);
	} catch (error) {
		return failure(`Writing ${patchPath} failed: ${describe(error)}\n\n${report}`);
	}
	return {
		result: {
			kind: 'success',
			text:
				`${report}\n\n${landed.replaced ? 'Updated' : 'Wrote'} ${patchPath}` +
				`${landed.backedUp ? ` (backup: ${patchPath}.bak-trim-preset)` : ''}.\n` +
				`Select preset "${presetId}" in the preset menu (reload the page if the menu is already open). ` +
				'A profile whose `patchReload` is `startup` only picks the row up at boot, so restart dsh if it never appears.'
		}
	};
}

/**
 * Print the routes a generated preset would cover — the poor man's dropdown.
 * @param ctx - plugin context.
 * @param agent - agent whose session supplies the active route.
 * @param signal - abort signal.
 * @param config - resolved plugin configuration (supplies the target ratio).
 * @returns a table of provider/model, window, output reserve and the reachable trigger.
 */
export async function renderRouteList(ctx, agent, signal, config = {}) {
	const routes = await collectRoutes(ctx, agent, signal);
	const targetRatio = config.compactionTargetRatio;
	const lines = [`Routes visible to the tuner (${routes.length}):`, ''];
	for (const route of routes) {
		const reserve = route.maxTokens ?? 0;
		// Floor like dsh does, so the printed trigger is the real one, not a rounded one.
		const reachable =
			route.contextWindow === undefined
				? 'no declared window'
				: `${Math.floor(Math.min(route.contextWindow * (targetRatio ?? 0.8), route.contextWindow - reserve))} tokens`;
		lines.push(`  ${route.provider}:${route.model}`);
		lines.push(`      contextWindow ${route.contextWindow ?? '?'} · maxTokens ${route.maxTokens ?? '?'} · trigger would be ~${reachable}`);
	}
	if (routes.length === 0) lines.push('  (none — is the llm-pi-ai row composed in this profile?)');
	return lines.join('\n');
}

/**
 * Read every configured route with the window and output reserve compaction uses.
 * @param ctx - plugin context.
 * @param agent - agent whose session is inspected for the active route.
 * @param signal - abort signal for model-info resolution.
 * @returns a de-duplicated `[{provider, model, contextWindow, maxTokens}]` list.
 */
export async function collectRoutes(ctx, agent, signal) {
	const routes = [];
	const seen = new Set();
	const push = (provider, model, contextWindow, maxTokens) => {
		if (typeof provider !== 'string' || typeof model !== 'string' || provider.length === 0 || model.length === 0) return;
		const key = `${provider}\u0000${model}`;
		if (seen.has(key)) return;
		seen.add(key);
		routes.push({ provider, model, contextWindow, maxTokens });
	};
	const active = latestRoute(agent.session);
	const configured = readConfiguredProviders(ctx);
	for (const [provider, profile] of configured) {
		const declared = Array.isArray(profile?.models) ? profile.models : [];
		if (declared.length > 0) {
			for (const model of declared) {
				const resolved = await resolveRoute(ctx, provider, model?.id, signal);
				push(provider, model?.id, resolved?.contextWindow ?? model?.contextWindow, resolved?.maxTokens ?? model?.maxTokens);
			}
			continue;
		}
		// Catalog-driven route: ask the adapter which models it serves.
		let ids = [];
		try {
			ids = (await ctx.llm.listModels(provider)) ?? [];
		} catch {
			ids = [];
		}
		for (const id of ids) {
			const resolved = await resolveRoute(ctx, provider, id, signal);
			push(provider, id, resolved?.contextWindow, resolved?.maxTokens);
		}
	}
	// The session's own route can be absent from the settings list (a model chosen
	// from the installed catalog); include it so the tuning covers what is in use.
	if (active !== undefined) {
		const resolved = await resolveRoute(ctx, active.provider, active.model, signal);
		push(active.provider, active.model, resolved?.contextWindow, resolved?.maxTokens);
	}
	return routes;
}

/** Resolve one route's adapter-owned window and default output cap, tolerating failure. */
async function resolveRoute(ctx, provider, model, signal) {
	if (typeof provider !== 'string' || typeof model !== 'string' || provider.length === 0 || model.length === 0) return undefined;
	try {
		const info = await ctx.llm.resolveModelInfo(provider, model, signal);
		return { contextWindow: info?.context?.contextWindow, maxTokens: info?.defaultMaxTokens };
	} catch {
		return undefined;
	}
}

/** Read the `llm-pi-ai` row's provider table from the composed configuration. */
function readConfiguredProviders(ctx) {
	const editor = ctx.get?.('configEditor');
	const entries = typeof editor?.entries === 'function' ? editor.entries() : [];
	const entry = entries.find((candidate) => candidate?.options?.id === 'llm-pi-ai');
	const providers = entry?.options?.config?.providers;
	return providers !== undefined && providers !== null && typeof providers === 'object' ? Object.entries(providers) : [];
}

/** Prefer the preset this session selected; fall back to the registry default. */
function pickBasePreset(roster, agent) {
	const presets = Array.isArray(roster?.presets) ? roster.presets : [];
	const selected = findSelectedPreset(agent);
	if (selected !== undefined) {
		const match = presets.find((preset) => preset.id === selected);
		if (match !== undefined) return match;
	}
	return presets.find((preset) => preset.isDefault === true) ?? presets[0];
}

/** The newest `agent-preset/selected` event, when the log carries one. */
function findSelectedPreset(agent) {
	const session = agent?.session;
	if (session === undefined || typeof session.eventAt !== 'function') return undefined;
	for (let seq = session.seq - 1; seq >= 0; seq -= 1) {
		const event = session.eventAt(seq);
		if (event?.type === 'agent-preset/selected' && typeof event.data?.agentPreset === 'string') return event.data.agentPreset;
	}
	return undefined;
}

/** Write the marker-delimited block atomically, keeping one rolling backup. */
async function persistBlock(patchPath, rowId, rowText) {
	let before = '';
	try {
		before = await readFile(patchPath, 'utf8');
	} catch (error) {
		if (error?.code !== 'ENOENT') throw error;
	}
	let backedUp = false;
	if (before.length > 0) {
		try {
			await copyFile(patchPath, `${patchPath}.bak-trim-preset`);
			backedUp = true;
		} catch {
			backedUp = false;
		}
	}
	const { text, replaced } = upsertMarkerBlock(before, rowId, rowText);
	const temporary = `${patchPath}.tmp-trim-${process.pid}`;
	await writeFile(temporary, text, 'utf8');
	await rename(temporary, patchPath);
	return { replaced, backedUp };
}

/** Human report: the route table, the planner's notes and the row preview. */
function renderReport({ base, plan, presetId, rowId, rowText, check }) {
	const lines = [
		`Compaction tuning from preset "${base.id}" → "${presetId}"${check ? ' (check: nothing written)' : ''}`,
		''
	];
	for (const note of plan.notes) lines.push(`  ${note}`);
	if (plan.skipped.length > 0) lines.push(`  skipped: ${plan.skipped.map((entry) => `${entry.provider}/${entry.model} (${entry.reason})`).join('; ')}`);
	lines.push('', `Generated patch row ${rowId} (${rowText.split('\n').length} lines):`, '');
	for (const line of rowText.split('\n').slice(0, 24)) lines.push(`  ${line}`);
	if (rowText.split('\n').length > 24) lines.push('  …');
	return lines.join('\n');
}

function failure(text) {
	return { result: { kind: 'error', text } };
}

function describe(error) {
	return error instanceof Error ? error.message : String(error);
}
