/**
 * Build the patch overlay that gives a *headless* (or otherwise preset-less) profile a
 * compaction-tuned preset and points the default at it.
 *
 * Why this exists: `agent-preset-registry` and the shipped `preset-*` rows are inserted
 * by `dsh-web-app` alone, so a headless profile (`dsh-base` + `dsh-headless`) composes
 * no preset plane at all — `/context-tune preset` cannot run there, because it clones the preset
 * in use through the registry. Automation still needs the tuned composition, so this
 * module builds the same two rows a web profile would end up with, from a base
 * composition read out of a shipped preset file:
 *
 *   1. `preset-<id>` — the base plugin list with the `compaction-basic` config replaced;
 *   2. `agent-preset-registry` — `default` and `selectedDefault` both pointing at it,
 *      which is what makes every subsequently created session start on it.
 *
 * Pure: no I/O and no dsh import, so it is unit-testable and usable from a script, a
 * test fixture, or CI setup.
 *
 * @module dsh-command-context-trim/tuned-preset
 */
import { renderCompactionConfig, renderPresetRow, renderRegistryRow, setEntryConfig } from './preset-yaml.js';

/** First line of every generated overlay, so the file explains itself. */
export const HOST_PATCH_HEADER =
	'# Generated by dsh-command-context-trim/scripts/make-preset-patch.mjs --mode host — the tuned\n' +
	'# compaction config written onto the PROFILE plane.\n' +
	'# Use this for profiles that compose compaction themselves (headless, tui): they never\n' +
	'# resolve a session preset, so a preset row would sit in the tree unused.';

export const PATCH_HEADER =
	'# Generated by dsh-command-context-trim/scripts/make-preset-patch.mjs — a compaction-tuned\n' +
	'# agent preset plus the registry row that makes it the default for new sessions.\n' +
	'# Delete this file (or stop passing --patch) to fall back to the shipped composition.';

/**
 * Compose the overlay for a profile that composes compaction itself (headless, tui).
 *
 * Verified behaviour behind this mode: a headless profile puts `compaction-basic` (plus
 * `command-compact` and `tool-result-pruner`) on the profile plane, and only the
 * session-API/web path ever resolves a session preset — a headless run composes the
 * same agent with or without a preset row in the tree. So on that plane the tuning has
 * to be written onto the row itself.
 * @param request - the tuning plan and the compaction row to override.
 * @returns `{ patch, config }` — file text and the config that was written.
 */
export function buildHostTunedPatch(request) {
	const { plan, rowId = 'compaction-basic', name = '@deepseek-ai/dsh-compaction-basic' } = request;
	if (plan === undefined || plan.config === undefined) throw new Error('tuned preset: a compaction plan is required');
	const row = [
		`- id: ${rowId}`,
		`  name: '${name}'`,
		...renderCompactionConfig(plan.config, 2)
	].join('\n');
	return { config: plan.config, patch: `${HOST_PATCH_HEADER}\n${row}\n` };
}

/**
 * Compose the overlay.
 * @param request - base plugin list, preset identity, the tuning plan and the registry mode.
 * @returns `{ patch, presetRow, plugins }` — the file text and its two parts.
 */
export function buildTunedPresetPatch(request) {
	const { base, presetId, name, description, order = 1.5, plan, registryMode = 'insert' } = request;
	if (typeof base !== 'string' || base.trim().length === 0) throw new Error('tuned preset: a base composition is required');
	if (typeof presetId !== 'string' || presetId.trim().length === 0) throw new Error('tuned preset: a preset id is required');
	if (plan === undefined || plan.config === undefined) throw new Error('tuned preset: a compaction plan is required');
	const plugins = setEntryConfig(base, 'compaction-basic', plan.config);
	if (plugins === null) {
		throw new Error('tuned preset: the base composition declares no compaction-basic entry to tune');
	}
	const presetRow = renderPresetRow({
		rowId: `preset-${presetId}`,
		presetId,
		name: name ?? presetId,
		description: description ?? 'compaction-tuned preset generated by dsh-command-context-trim',
		order,
		pluginsYaml: plugins
	});
	const registryRow = renderRegistryRow({ presetId, mode: registryMode });
	return {
		plugins,
		presetRow,
		registryRow,
		patch: `${PATCH_HEADER}\n${presetRow}\n\n${registryRow}\n`
	};
}
